site_name: Rowl1ng的人生魔法书
repo_url: https://github.com/Rowl1ng/MyWiki.git
repo_name: MyWiki

theme:
  name: material
  language: zh
  custom_dir: theme/
  logo: images/logo-rowl1ng.png
  favicon: images/favicon.ico
  features:
    - content.code.annotate
    - navigation.top
    - navigation.tabs
    - navigation.indexes
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://cdn.jsdelivr.net/npm/mermaid@10.1.0/dist/mermaid.min.js'
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: zh
  - git-authors:
      show_contribution: true
      show_line_count: true

validation:
  absolute_links: ignore
  unrecognized_links: ignore

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - def_list
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - meta
  - pymdownx.highlight:
      linenums: true
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format

# Contents
nav:
  - 首页:
    - README.md
    - Research: research/README.md
    - Math: math/README.md
    - Machine Learning: machine_learning/README.md
    - Computer Graphics: computer_graphics/README.md
    - Computer Vision: computer_vision/README.md
    - Programming: programming/README.md
    - Language: language/README.md
    - Art: art/README.md
    - Music: music/README.md
  - Research:
      - Writing papers: research/writing_papers.md
      - Latex: research/latex.md
      - Presentation: research/presentation.md
      - Projects: research/projects.md

  - Math:
      - Probability Theory: math/probability.md
      - Nonliner Optimization:
          - Nonliner Optimization: math/optimization/optimization.md
          - Introduction: math/optimization/introduction.md
          - SMO: math/optimization/smo.md
          - 优化算法: math/optimization/optimizer.md

  - Machine Learning:
      - Introduction: machine_learning/README.md
      - Part -1 Data Analysis:
          - Data Analysis: machine_learning/data_analysis/data_analyse.md
          - scikit-learn: machine_learning/data_analysis/scikit-learn.md
          - pandas: machine_learning/data_analysis/pandas.md
          - Jupyter: machine_learning/data_analysis/jupyter.md
          - numpy:
              - numpy: machine_learning/data_analysis/numpy.md
              - array: machine_learning/data_analysis/numpy/array.md
      - Part 0 Math Basics:
          - Math Basics: machine_learning/math/chapter1.md
          - inbox: machine_learning/math/inbox0.md
          - functions: machine_learning/math/function.md
          - Derivatives: machine_learning/math/differential.md
          - Integrals: machine_learning/math/integral.md
          - matrix: machine_learning/math/matrix.md
          - Probability: machine_learning/math/probability.md
          - Metrics: machine_learning/math/metrics.md
          - Distance: machine_learning/math/distance.md
          - Terminology: machine_learning/math/term.md.md
      - Part 1 Basic Concepts:
          - Basic Concepts: machine_learning/basics/basic.md
          - Overview: machine_learning/basics/generality.md
          - 基础学习算法: machine_learning/basics/svm.md
          - Convolution: machine_learning/basics/convolution.md
          - CRF: machine_learning/basics/crf.md
          - normalization: machine_learning/basics/normalization.md
          - regularization: machine_learning/basics/regularization.md
      - Part 2 NN from scratch:
          - NN from scratch: machine_learning/nn/nnintro.md
          - functions: machine_learning/nn/nnfunction.md
          - activation function: machine_learning/nn/activation-function.md
          - loss function: machine_learning/nn/loss-function.md
          - NN Structure: machine_learning/nn/nnstructure.md
          - Regularized Networks: machine_learning/nn/regulizer.md
          - RNN: machine_learning/nn/rnn.md
          - CNN: machine_learning/nn/cnn.md
          - Criterion: machine_learning/nn/criterion.md
          - Backbone: machine_learning/nn/backbone.md
          - Terms: machine_learning/nn/termsmd.md
          - boost: machine_learning/nn/boost.md
          - Attention: machine_learning/nn/attention.md
      - Part 3 Problems:
          - Problems: machine_learning/problems/README.md
          - Generative Model: machine_learning/problems/generative-model.md
          - Transfer Learning: machine_learning/problems/transfer-learning.md
          - Few-shot Learning: machine_learning/problems/few-shot-learning.md
          - sample imbalance: machine_learning/problems/imbalance.md
          - unsupervised learning: machine_learning/problems/unsupervised-learning.md
          - Metric Laerning: machine_learning/problems/metric-learning.md
      - Part 4 NN Programming:
          - NN Programming: machine_learning/programming/nnpractice.md
          - keras: machine_learning/programming/keras.md
          - Theano: machine_learning/programming/theano.md
          - Tensorflow: machine_learning/programming/tensorflow.md
          - caffe: machine_learning/programming/caffe.md
          - layer: machine_learning/programming/layer.md
          - matlab: machine_learning/programming/matlab.md
          - Pytorch: machine_learning/programming/pytorch.md
          - method: machine_learning/programming/method.md
      - Part 6 Applications:
          - Applications: machine_learning/application/README.md
          - Explore DL: machine_learning/application/deeplearning.md
          - word2vec: machine_learning/application/word2vec.md
          - AlphaGo: machine_learning/application/alphago.md
          - 自动漏洞挖掘: machine_learning/application/automated_vulnerability_detection.md

  - Computer Graphics:
      - Introduction: computer_graphics/README.md
      - Basics:
          - Basics: computer_graphics/basics/README.md
          - Geometry Processing: computer_graphics/basics/geometry-processing.md
          - 3D Vison: computer_graphics/basics/3D-vision.md
          - metrics: computer_graphics/basics/metrics.md
      - Data Analysis:
          - Data Analysis: computer_graphics/programming/README.md
          - Visualization: computer_graphics/programming/visualization.md
          - blender: computer_graphics/programming/blender.md
          - Point Cloud: computer_graphics/programming/point-cloud.md
      - Tasks:
          - Tasks: computer_graphics/tasks/tasks.md
          - Shape Deformation: computer_graphics/tasks/shape_deformation.md
          - Shape Retrieval: computer_graphics/tasks/shape_retrieval.md
          - VR Sketch: computer_graphics/tasks/VR_Sketch.md

  - Computer Vision:
      - Introduction: computer_vision/README.md
      - Image Processing Basics:
          - Image Processing Basics: computer_vision/basics/image_basics.md
          - filter: computer_vision/basics/filter.md
          - feature: computer_vision/basics/feature.md
          - image normalization: computer_vision/basics/image_normalization.md
          - thresholding: computer_vision/basics/thresholding.md
      - python programming:
          - python programming: computer_vision/python_programming/python_programming.md
          - opencv: computer_vision/python_programming/opencv.md
          - matplotlib: computer_vision/python_programming/matplotlib.md
          - scikit-image: computer_vision/python_programming/skimage.md
          - visualize: computer_vision/python_programming/visualize.md
          - FROC: computer_vision/python_programming/froc.md
          - patch: computer_vision/python_programming/patch.md
      - Problems:
          - Problems: computer_vision/problems/ren-wu.md
          - segmentation: computer_vision/problems/segmentation.md
          - detection: computer_vision/problems/detection.md
      - Practices:
          - Practices: computer_vision/applications/practice.md
          - Medical Image Analysis: computer_vision/applications/medical_image_analysis.md
          - Mammogram: computer_vision/applications/mammogram.md
          - Road Crack Detection: computer_vision/applications/roadnn.md
          - Road Lane Recognition: computer_vision/applications/lane.md

  - Programming:
      - 编程: programming/programming.md
      - Python Handbook:
          - Python Handbook: programming/python/README.md
          - 基础: programming/python/basics.md
          - 文件: programming/python/file.md
          - 多线程: programming/python/multiproccessing.md
          - 数据库: programming/python/database.md
          - 编码: programming/python/code.md
          - 调试: programming/python/debug.md
          - 日志: programming/python/log.md
          - 模块: programming/python/module.md
          - 面向对象编程: programming/python/OOP.md
          - 错误和异常: programming/python/error.md
          - cython: programming/python/cython.md
          - 高级特性: programming/python/superior.md
          - 函数式编程: programming/python/functional.md
      - linux:
          - linux: programming/linux/linux.md
          - train&test: programming/linux/trainandtest.md
      - Windows: programming/windows.md

  - Language:
      - English:
          - English: language/English/README.md
          - suffix: language/English/suffix.md
          - prefix: language/English/prefix.md
          - verb: language/English/verb.md
          - synonym: language/English/synonym.md
          - math: language/English/math.md
          - material: language/English/material.md
      - 日本語: language/japanese.md
      - Francis: language/francis.md
      - others: language/others.md

  - Art:
      - color: art/color.md
      - light: art/light.md

  - Music:
      - Inbox: music/inbox.md
      - 古琴: music/guqin.md